version: "3.7"
services:
  java-maven-app:
    image: ${IMAGE_NAME}
    ports:
      - 8080:8080
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass
